/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function calculateSha256(inputBytes: Uint8Array): string
export declare function calculateSha384(inputBytes: Uint8Array): string
export declare function calculateSha512(inputBytes: Uint8Array): string
