name: Publish Packages

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build bindings and node packages
    uses: ./.github/workflows/reusable-release-build.yml

  publish:
    if: github.repository == 'Assone/unplugin-sri'
    name: Publish npm packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Download Binding Artifacts
        uses: actions/download-artifact@v4
        with:
          path: algorithm/sha/artifacts

      - name: Move artifacts
        run: |
          pnpm --filter=@unplugin-sri/algorithm-sha run artifacts

      - name: List packages
        run: ls -R ./algorithm/sha/npm
        shell: bash

      - name: Download Node Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/sri/dist
          name: node-artifact

      - name: Set Publishing Config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env: 
          NPM_TOKEN: ${{ secrets.UNPLUGIN_SRI_NPM_TOKEN }}

      - name: Publish(Dry Run)
        run: |
          pnpm publish -r --tag latest --dry-run --no-git-check
        env:
          NPM_TOKEN: ${{ secrets.UNPLUGIN_SRI_NPM_TOKEN }}

      - name: Publish
        run: |
          pnpm publish -r --tag latest --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.UNPLUGIN_SRI_NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true